version: '3'

services:
  db:
    container_name: 'mysql-container'
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_ROOT_PASSWORD=Bodepreto20!
    networks:
        - app-network
        
  app:
    container_name: 'backend-container'
    build: .
    # This command serves to wait for the mysql database boot to before run the backend server
    #   - need the database's port to run
    command: > 
      bash -c 'timeout $TIMEOUT sh -c "while !</dev/tcp/db/$DB_PORT; do sleep 1; done;npm run dev"'
    ports:
      - '3535:3535'
    environment:
      - PORT=3535
      - DB_PORT=3306
      - TIMEOUT=60

    depends_on:
      db:
        condition: service_started
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
